# Generated by Django 4.0.5 on 2022-07-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
    ]
