# Generated by Django 4.0.5 on 2022-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0002_rename_body_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Post', max_length=255),
        ),
    ]
