# Generated by Django 4.0.5 on 2022-07-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0003_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
