# Generated by Django 4.0.5 on 2022-07-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0004_post_budget_post_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.IntegerField(),
        ),
    ]
