# Generated by Django 4.0.6 on 2022-07-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0015_post_category2_post_category3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='terms',
            field=models.IntegerField(null=True),
        ),
    ]
