# Generated by Django 4.0.6 on 2022-07-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0018_profile_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
