# Generated by Django 3.2 on 2022-07-19 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesite', '0019_remove_profile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Unemployed', max_length=255),
        ),
    ]
